feat: add toast
radix-vue/shadcn-vue pull request #122
Opened 2023-10-15 18:42 UTC by nkutinha

PR for https://github.com/radix-vue/shadcn-vue/issues/56.

Please, feel free to share your thoughts on this. Once you're satisfied, I'll happily transfer it to the New York theme :)

2023-10-17 06:40 UTC, sadeghbarati requested changes

2023-10-17 06:40 UTC, sadeghbarati commented on apps/www/src/lib/registry/default/ui/toast/Toast.vue
> +};
Thank you for PR

If you look into main `radix-vue` source, they are using normal script alongside script setup for exporting types

```suggestion
<script lang="ts">
import type { VariantProps } from 'class-variance-authority'

export interface ToastProps extends ToastRootProps, VariantProps<typeof toastVariants> {
  class?: string
};
</script>
<script setup lang="ts">
```

2023-10-30 19:30 UTC, sadeghbarati commented
Thank you for PR @nkutinha 

Sry I pushed some changes without your permission

2023-11-03 01:45 UTC, merged

2023-11-03 01:46 UTC, zernonia commented
Thanks for the PR @nkutinha ! And the review @sadeghbarati ! 
Well done  🚀!