Fix bug in code example combobox.md
radix-vue/shadcn-vue pull request #420
Opened 2024-03-21 09:21 UTC by devbyray

The default value of `const value = ref({})` should contain a falsy value in order to show the "Select framework...".

![image](https://github.com/radix-vue/shadcn-vue/assets/6241164/04496c48-bfb3-47a7-a48b-3dce5b1d4c22)

![image](https://github.com/radix-vue/shadcn-vue/assets/6241164/71df90ec-e0e2-4e0e-9a14-2587a1312e34)

When giving it an `{}` empty object will result in a truthy value which is not what we want. When given an a falsy value like `null` it will display the correct text in the button.

2024-03-21 09:47 UTC, sadeghbarati requested changes

2024-03-21 09:47 UTC, sadeghbarati commented on apps/www/src/content/docs/components/combobox.md
> +const value = ref(null)
I think empty string will dose the trick

```suggestion
const value = ref('')
```

2024-03-21 09:47 UTC, sadeghbarati commented on apps/www/src/content/docs/components/combobox.md
> +        {{ value ? frameworks.find((framework) => framework.value === value?.value)?.label : 'Select framework...' }}
based on [`ComboboxDemo.vue`](https://github.com/radix-vue/shadcn-vue/blob/dev/apps/www/src/lib/registry/default/example/ComboboxDemo.vue)

There is no need to use `.value` in `<template>`

```suggestion
        {{ value ? frameworks.find((framework) => framework.value === value)?.label : 'Select framework...' }}
```

2024-03-21 15:24 UTC, devbyray commented
@sadeghbarati thanks for your suggestions. It appears that the Codesandbox example is different then the one in the Markdown file: https://codesandbox.io/p/devbox/shadcn-vue-comboboxdemo-368j7c?file=%2Fsrc%2FApp.vue

The `:value="framework"` in the Markdown example uses the whole object as value. In the Codesandbox it is `:value="framework.value"`. 

![image](https://github.com/radix-vue/shadcn-vue/assets/6241164/67ddc097-46ab-4a8b-bc10-1fb33c71fde9)

2024-03-21 15:31 UTC, sadeghbarati commented on apps/www/src/content/docs/components/combobox.md
> +                  value?.value === framework.value ? 'opacity-100' : 'opacity-0',
```suggestion
                  value === framework.value ? 'opacity-100' : 'opacity-0',
```

2024-03-21 15:45 UTC, sadeghbarati approved these changes

2024-03-21 15:46 UTC, merged

2024-03-25 12:28 UTC, devbyray commented
@sadeghbarati I'm to see the fix being merged 💪